project_id = "hqjszktwczdnyyomllzd"

[functions.scrape-news]
verify_jwt = false

[functions.summarize-article]
verify_jwt = false

[functions.batch-summarize]
verify_jwt = false

[functions.generate-og-image]
verify_jwt = false

[functions.generate-article-image]
verify_jwt = false

[functions.share-meta]
verify_jwt = false